Add F111 model
Sygil-Dev/nataili-model-reference pull request #4
Opened 2022-11-03 15:19 UTC by reacharound

First time doing this, hope I didn't break anything.

2022-11-03 15:28 UTC, db0 requested changes
Hey thanks for contributing. This need a bit of work to be ready. Please check the comments I've left you and adjust

2022-11-03 15:28 UTC, db0 commented on db.json
> +        "file_path", "models/custom",
You have a mistake here. it should be colon `:` and not comma

2022-11-03 15:28 UTC, db0 commented on db.json
> +    "description": "Nude solo women",
Try to be a bit more flowery with the style if possible. See how the other descriptions are.

For example: "Style focused on drawing nude solo women"

2022-11-03 15:28 UTC, db0 commented on db.json
> +    "version": "111",
Version is unlikely to be 111 (unless F111 has published 110 other versions of this model). If you don't know the version, just put 1 here

2022-11-03 15:28 UTC, db0 commented on db.json
> +          "path": "models/custom/waifu-diffusion.ckpt",
You need to put `f111.ckpt` here instead of `waifu_diffusion.ckpt`

2022-11-03 15:28 UTC, db0 commented on db.json
> +          "md5sum": "ed119c704e6a33cb5362e5f0e0455ad0"
Did you calculate the md5sum here, or just copied it from another entry? If you didn't calculate it, just remove this line and the comma in the line above

2022-11-03 18:09 UTC, reacharound commented on db.json
> +    "nsfw": true,
There is no specific trigger word, the idea is to use it as if it were base SD. Unless you want me to create one?

2022-11-03 18:11 UTC, reacharound commented on db.json
> +    "version": "111",
The previous version was called F99 and I think the previous one was F98, I don't know what came before that though. The next is meant to be F222. I'll put version 3 since I know there were at least 2 more.

2022-11-03 18:14 UTC, reacharound commented on db.json
> +          "md5sum": "ed119c704e6a33cb5362e5f0e0455ad0"
I used an online md5sum calculator, using the filepath. If it's better I'll delete it.

2022-11-03 20:04 UTC, db0 commented on db.json
> +          "md5sum": "ed119c704e6a33cb5362e5f0e0455ad0"
If you pointed it to the locally downloaded file, it should be OK. We'll find out if it's a problem on the first rtun anyway

2022-11-03 20:05 UTC, db0 commented on db.json
> +    "nsfw": true,
This is not a dreambooth model?

2022-11-03 20:05 UTC, db0 commented on db.json
> +    "version": "111",
What is this naming convention lol.

So the model name changes every time?

2022-11-03 20:48 UTC, reacharound commented on db.json
> +    "nsfw": true,
I imagine it is since the website says  'Dreamboth Models' but I asked in the discord if there was a trigger word and the owner said no.

2022-11-03 20:51 UTC, reacharound commented on db.json
> +    "version": "111",
What about 'Zeipher Female Model' for name, cause he has other models too

2022-11-03 20:54 UTC, reacharound commented on db.json
> +    "version": "111",
The 'F' is for Female

2022-11-03 22:01 UTC, db0 commented on db.json
> +    "version": "111",
Works for me. Let's go this direction

2022-11-03 22:02 UTC, db0 commented on db.json
> +    "nsfw": true,
This is strange. Ok skip the trigger style, but change the type to 'NSFW' instead of dreambooth.

2022-11-03 22:04 UTC, db0 requested changes

2022-11-03 22:04 UTC, db0 commented on db.json
> +    "download_all": true,
Change download_all to false here.

2022-11-04 08:50 UTC, db0 approved these changes

2022-11-04 08:56 UTC, merged

2022-11-04 09:04 UTC, db0 commented
Looks like this repo doesn't exist anymore